repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
      - id: fmt
        args: ["--verbose", "--edition", "2018", "--"]
      - id: clippy
      - id: cargo-check
  - repo: local
    hooks:
      - id: cargo-test
        name: Run cargo test
        entry: cargo test
        language: script
        pass_filenames: false
        types: [rust]
